<?php
/**
 * @file
 * Contains blaetter_formatters.module.
 */

use Drupal\Core\Entity\ContentEntityInterface;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\field\Entity\FieldStorageConfig;

/**
 * Implements hook_help()
 *
 * @param string              $route_name  The name of the route
 * @param RouteMatchInterface $route_match The route match interface object
 *
 * @see hook_help()
 * )
 * @return void
 */
function blaetter_formatters_help(string $route_name, RouteMatchInterface $route_match)
{
    switch ($route_name) {
        // Main module help for the nodeshop module.
        case 'help.page.blaetter_formatters':
            $output = '';
            $output .= '<h3>' . t('About') . '</h3>';
            $output .= '<p>' . t(
                'This module adds formatters to Drupal fields. Currently there are the following formatters:'
            ) . '</p>';
            $output .= '<ul>';
            $output .= '<li>' . t(
              '<strong>Blätter inline formatter</strong>: This formatter takes entity references and displays their ' .
              'values inline with a configurable seperator. You can also specify an optional prefix and decide, if ' .
              'values should be linked to its entity pages or not.'
            ) . '</li>';
            $output .= '</ul>';
            return $output;
        default:
    }
}

/**
 * Implements hook_theme()
 *
 * @see hook_theme()
 *
 * @return void
 */
function blaetter_formatters_theme()
{
    return [
      'blaetter_embed_block' => [
        'template'  => 'blaetter_embed_block',
        'variables' => [
          'embed'         => [],
        ]
      ],
      'blaetter_formatters_inline' => [
        'template'  => 'blaetter_formatters_inline',
        'variables' => [
          'entities'      => [],
          'separator'     => '',
          'prefix'        => '',
        ]
        ],
      'blaetter_formatters_issue' => [
        'template'  => 'blaetter_formatters_issue',
        'variables' => [
          'book_id'       => '',
          'edition'       => '',
          'year'          => '',
          'display_pages' => '',
          'page_from'     => '',
          'page_to'       => '',
          'issue_prefix'  => '',
          'extra_styles'  => ''
        ]
      ],
      'blaetter_grid_block' => [
        'template'    => 'blaetter_grid_block',
          'variables' => [
          'grid_class_left'   => '',
          'grid_class_right'  => '',
          'title'             => '',
          'title_left'        => '',
          'content_left'      => '',
          'title_right'       => '',
          'content_right'     => '',
        ]
      ],
      'blaetter_grid_block_title' => [
        'template'  => 'blaetter_grid_block_title',
        'variables' => [
          'title'         => '',
        ]
      ]
    ];
}

/**
 * Set dynamic allowed values for the provider field of the media type oembed.
 *
 * @param \Drupal\field\Entity\FieldStorageConfig $definition
 *   The field definition.
 * @param \Drupal\Core\Entity\ContentEntityInterface|null $entity
 *   The entity being created if applicable.
 * @param bool $cacheable
 *   Boolean indicating if the results are cacheable.
 *
 * @return array
 *   An array of possible key and value options.
 *
 * @see options_allowed_values()
 */
function blaaetter_formatters_allowed_media_providers(FieldStorageConfig $definition, ContentEntityInterface $entity = NULL, $cacheable) {
  $options = [];
  if (null !== $entity && 'generic_iframe' == $entity->bundle()) {
    $options = [
      'Detektor.fm' => 'Detektor.fm',
      'Google Maps' => 'Google Maps',
    ];
  } elseif (null !== $entity && 'remote_video' == $entity->bundle()) {
    $options = [
      'YouTube' => 'YouTube',
      'Vimeo' => 'Vimeo',
    ];
  }
  return $options;
}


/**
 * implements hook_mail_alter()
 * @author Paul Reny
 * @author Christoph Heger
 * @author Andreas Mängel
 * Custom format the contact us form, otherwise it's full of nbsp terribleness
 */
function blaetter_formatters_mail_alter(&$message) {
  // only alter contact forms
  if (!empty($message['id'])
    && (
      $message['id'] == 'contact_page_mail' || $message['id'] == 'contact_page_copy'
    )
  ) {

      // get the contact message object
      $contact_message = $message['params']['contact_message'];
      // get the senders user object
      $sender = $message['params']['sender'];

      // check if we have a category and set up the subject if so
      if ($contact_message->hasField('field_category') && !empty($contact_message->get('field_category')->value)) {
        $message['subject'] = str_replace(
          'Website-Feedback',
          $contact_message->get('field_category')->value,
          $message['subject']
        );
      }

      // empty the body
      $message['body'] = [];

      // get the fields and rebuild the body
      $fields = $contact_message->getFields();
      $new_body = '';

      if ('contact_page_mail' == $message['id']) {
        $new_body .= $contact_message->get('name')->value . ' hat folgende Nachricht über das Kontaktformular auf ' .
        'https://www.blaetter.de/contact geschickt:' . PHP_EOL . PHP_EOL;
      } elseif ('contact_page_copy' == $message['id']) {
        $new_body .= 'Hallo ' . $contact_message->get('name')->value . ',' . PHP_EOL . PHP_EOL;
        $new_body .= 'vielen Dank für Ihre Anfrage, wir haben folgende Nachricht von Ihnen erhalten: ' . PHP_EOL . PHP_EOL;
      }

      $new_body .= $contact_message->get('message')->value . PHP_EOL . PHP_EOL;

      foreach ($fields as $field_name => $field) {
          // as we use the category for the subject, there is no need to display it again here.
          if ('field_category' == $field_name) {
            continue;
          }
          if (get_class($field->getFieldDefinition()) == 'Drupal\field\Entity\FieldConfig') {
              $new_body .= $field->getFieldDefinition()->label() . ':' . PHP_EOL .
                  $contact_message->get($field_name)->value . PHP_EOL . PHP_EOL;
          }
      }
      $new_body .= '==' . PHP_EOL;
      $new_body .= 'Ihre »Blätter«' . PHP_EOL;
      $message['body'][] = $new_body;
  }
}
